apiVersion: v1
kind: Service

metadata:
  name: chat-service

spec:
  type: ClusterIP
  selector:
    app: chat-app
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8083