apiVersion: v1
kind: Pod

metadata:
  name: chat-pod-1

spec:
  containers:
    - name: chat-container
      image: docker.io/jeongchanmin/spring-server:0.1.2
      ports:
        - containerPort: 8080
      imagePullPolicy: Always

---
apiVersion: v1
kind: Pod

metadata:
  name: chat-pod-2

spec:
  containers:
    - name: chat-container
      image: docker.io/jeongchanmin/spring-server:0.1.2
      ports:
        - containerPort: 8080
      imagePullPolicy: Always

---
apiVersion: v1
kind: Pod

metadata:
  name: chat-pod-3

spec:
  containers:
    - name: chat-container
      image: docker.io/jeongchanmin/spring-server:0.1.2
      ports:
        - containerPort: 8080
      imagePullPolicy: Always