apiVersion: v1
kind: Service

metadata:
  name: report-service

spec:
  type: LoadBalancer
  selector:
    app: report-app
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      # nodePort: 30001
