apiVersion: apps/v1
kind: Deployment

metadata:
  name: report-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-app

  template:
    metadata:
      labels:
        app: report-app
    spec:
      containers:
        - name: report-container
          image: paaspaas.kr.ncr.ntruss.com/repoort-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      imagePullSecrets:
        - name: report-server-image-secret