apiVersion: v1
kind: Service

metadata:
  name: front-service

spec:
  type: ClusterIP
  selector:
    app: front-app
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 3000
