spring:
  application:
    name: front-server
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
  profiles:
    active: prod

server:
  port: 8080

---
# Local 환경 설정
spring:
  config:
    activate:
      on-profile: local

api:
  gateway:
    url: http://localhost:8000

---
# Production 환경 설정
spring:
  config:
    activate:
      on-profile: prod

api:
  gateway:
    url: http://default-gateway-service-3c796-111636377-d0c75d212fa0.kr.lb.naverncp.com:8080
