apiVersion: apps/v1
kind: Deployment

metadata:
  name: document-deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      app: document-app

  template:
    metadata:
      labels:
        app: document-app
    spec:
      containers:
        - name: document-container
          image: paaspaas.kr.ncr.ntruss.com/document-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: document-config
            - secretRef:
                name: document-secret
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: document-config
                  key: spring-profiles-active
            - name: CONSUMER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

      imagePullSecrets:
        - name: document-server-image-secret
