apiVersion: v1
kind: Service

metadata:
  name: chat-service

spec:
  type: NodePort
  selector:
    app: chat-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
