apiVersion: v1
kind: ConfigMap

metadata:
  name: document-config

data:
  # Spring profile
  spring-profiles-active: prod

  # DB
  db-host: mysql-service
  db-port: "3306"
  db-name: chatdb

  redis-host: redis-service
  redis-port: "6379"

  # OpenAI
  openai-model: gpt-4o-mini
  openai-api-url: https://api.openai.com/v1/chat/completions

  # Clova OCR
  clova-ocr-api-url: https://trradxiath.apigw.ntruss.com/custom/v1/46757/8d41fb2ded8882cfbcf2fb55ebd24b179269bb75543d7f3931924549a656e1d8/general
