apiVersion: v1
kind: Service

metadata:
  name: document-service

spec:
  type: NodePort
  selector:
    app: document-app
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      # nodePort: 30001
