apiVersion: v1
kind: Service

metadata:
  name: member-service

spec:
  type: ClusterIP
  selector:
    app: member-app
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8081

