apiVersion: v1
kind: Service

metadata:
  name: document-redis-service

spec:
  selector:
    app: document-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  clusterIP: None