server:
  port: 8082

spring:
  application:
    name: document-server

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

# Gateway Configuration (for Swagger)
gateway:
  url: ${GATEWAY_URL:http://localhost:8080}

# SpringDoc (Swagger) Configuration
springdoc:
  api-docs:
    path: /document/v3/api-docs
  swagger-ui:
    path: /document/swagger-ui.html