spring:
  application:
    name: document-server

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}