apiVersion: v1
kind: Service

metadata:
  name: nlp-service

spec:
  type: LoadBalancer
  selector:
    app: nlp-app
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      # nodePort: 30001
