apiVersion: v1
kind: Service

metadata:
  name: gateway-service

spec:
  type: ClusterIP
  selector:
    app: gateway-app
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
