server:
  port: 8083
logging:
  level:
    reactor.netty: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.web.reactive.client.ExchangeFunctions: TRACE
    org.springframework.web.server: DEBUG
    root: info
    com.example.chat: debug

app:
  audio:
    # 내 PC의 로컬 경로
    ffmpeg-path: "C:\\ffmpeg\\bin\\ffmpeg.exe"
  gcp:
    # 내 PC의 서비스 계정 키 경로
    sa.path: C:/keys/paas-paas-1218c3347d8e.json

spring:
  config:
    # 로컬에서만 비밀 설정 파일을 읽어옴
    import: "optional:classpath:application-secret.yml"