server:
  port: 8080
logging:
  level:
    reactor.netty: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.web.reactive.client.ExchangeFunctions: TRACE
    org.springframework.web.server: DEBUG
    root: info
    com.example.chat: debug

app:
  audio:
    ffmpeg-path: "C:\\ffmpeg\\bin\\ffmpeg.exe"
    mock:
      enabled: false
      on: META
      sample: classpath:/mock/sample-tts.ogg
  stt:
    base-url: https://naveropenapi.apigw.ntruss.com
    path: /recog/v1/stt
    language: Kor
    connect-timeout-ms: 3000
    read-timeout-ms: 60000
  trans:
    baseurl: https://papago.apigw.ntruss.com
    path: /nmt/v1/translation
    source: auto
    target: ko
    connect-timeout-ms: 3000
    read-timeout-ms: 60000
  llm:
    base-url: "https://generativelanguage.googleapis.com"
    connection-timeout-ms: 1000
    read-timeout-ms: 60000
  vertex:
    search-base-url: "https://discoveryengine.googleapis.com"
    project-id: "paas-paas"
    location: "global"
    scope: "https://www.googleapis.com/auth/cloud-platform"
    http:
      connection-timeout-ms: 1500
      read-timeout-ms: 60000

spring:
  main:
    web-application-type: reactive
  config:
    import: "optional:classpath:application-secret.yml"
