spring:
  config:
    import: optional:file:chat-server/.env[.properties]

logging:
  level:
    reactor.netty: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.web.reactive.client.ExchangeFunctions: TRACE
    org.springframework.web.server: DEBUG
    root: INFO
    com.example.chat: DEBUG

app:
  audio:
    ffmpeg-path: ${FFMPEG_PATH:C:\\ffmpeg\\bin\\ffmpeg.exe}
  gcp:
    sa.path: ${GCP_SA_PATH:C:/keys/paas-paas-1218c3347d8e.json}
  stt:
    api-key-id: ${APP_STT_API_KEY_ID}
    api-key: ${APP_STT_API_KEY}
  trans:
    api-key-id: ${APP_TRANS_API_KEY_ID}
    api-key: ${APP_TRANS_API_KEY}
  llm:
    api-key: ${APP_LLM_API_KEY}
  vertex:
    data-store-id: ${APP_VERTEX_DATA_STORE_ID}