app:
  stt:
    api-key-id: v7ro26lsy3
    api-key: QBBNNmDYiUAHC2aedddfQGCc5htaE0wmAUcFQXv0
  trans:
    api-key-id: skp47zzw0u
    api-key: f3xeEPb1aqtiSKudTQBl0QaH7iw40rP6NWqilxTF
  llm:
    api-key: AIzaSyB0lsTZwCZnrzD8f7a5fM4Ki5ybRK2yDj4
  vertex:
    data-store-id: "paas-paas-search_1760351497448"
