server:
  port: 8080
logging:
  level:
    reactor.netty: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.web.server: DEBUG
    root: info
    com.example.chat: debug

app:
  audio:
    ffmpeg-path: "C:\\ffmpeg\\bin\\ffmpeg.exe"
    mock:
      enabled: false
      on: META
      sample: classpath:/mock/sample-tts.ogg
  stt:
    base-url: https://naveropenapi.apigw.ntruss.com
    path: /recog/v1/stt
    language: Kor
    connect-timeout-ms: 3000
    read-timeout-ms: 15000


spring:
  main:
    web-application-type: reactive
  config:
    import: "optional:classpath:application-secret.yml"
