app:
  stt:
    base-url: https://naveropenapi.apigw.ntruss.com
    path: /recog/v1/stt
    language: Kor
    connect-timeout-ms: 3000
    read-timeout-ms: 60000
  trans:
    baseurl: https://papago.apigw.ntruss.com
    path: /nmt/v1/translation
    source: auto
    target: ko
    connect-timeout-ms: 3000
    read-timeout-ms: 60000
  llm:
    base-url: "https://generativelanguage.googleapis.com"
    connection-timeout-ms: 1000
    read-timeout-ms: 60000
  vertex:
    search-base-url: "https://discoveryengine.googleapis.com"
    project-id: "paas-paas"
    location: "global"
    scope: "https://www.googleapis.com/auth/cloud-platform"
    http:
      connection-timeout-ms: 1500
      read-timeout-ms: 60000
  gcp:
    project-id: "paas-paas"
    # sa.path: (삭제 -> local/prod 파일로 이동)

spring:
  main:
    web-application-type: reactive
  config:
  profiles:
    active: local


