server:
  port: 8080
logging:
  level:
    reactor.netty: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.web.server: DEBUG
    root: info
    com.example.chat: debug

app:
  audio:
    mock:
      enabled: true
      on: META
      sample: classpath:/mock/sample-tts.ogg